- name: Create user
  become: true
  user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    create_home: true
    shell: /usr/bin/bash
    append: yes
    groups:
      - adm
      - cdrom
      - sudo
      - dip
      - plugdev
      - input
      - lpadmin
      - sambashare
