---

- name: System setup
  hosts: home
  roles:
    - system/bootstrap
    - system/xps_9560_tweaks
    - apps/desktop
    - apps/development
    - user/creation
    - user/config_files
    - user/fish_shell
    - crontab
  vars:
    # Make sure you change your password on first login
    user:
      name: luis
      password: password
